### ISSUE TITLE
Download MP3 format data set

### ISSUE THREAD

**Issue by yangdaowu** [francesclluis/point-cloud-source-separation#1]
Seeing from the issues, this is a common request. How do we download the video files using the .JSON file? How can we pre-process to extract the downloaded videos into the format.

**Comment by francesclluis** [comment]
Hi! 
I used the following script to download videos from youtube using the .JSON file: [https://github.com/JuanFMontesinos/Solos/blob/master/youtubesaver.py](https://github.com/JuanFMontesinos/Solos/blob/master/youtubesaver.py)
Then I used [ffmpeg](http://ffmpeg.org/) to process and extract the audio into the format. You could do in python something like:
```
videos_folder = 'VIDEOS_FOLDER_PATH'
audios_folder = 'EXTRACTED_AUDIOS_FOLDER_PATH'
filenames = [filename for filename in os.listdir(videos_folder) if filename.endswith('.mp4')]
for filename in filenames:
     os.system("ffmpeg -i {0} -ar 11025 {1}".format(os.path.join(videos_folder, filename), os.path.join(audios_folder, filename[:-4]+'.mp3')))
```

**Comment by yangdaowu** [comment]
是的，我正在尝试，我能下载mp4格式的视频，它也可以播放出来，但遇到了问题，我只能一个一个下载：
![image](https://user-images.githubusercontent.com/64669901/125588512-914b1b64-ac25-4fe2-be5a-675327af454e.png)
