### ISSUE TITLE
Evaluation index of multiple musical instruments

### ISSUE THREAD

**Issue by yangdaowu** [francesclluis/point-cloud-source-separation#2]
Hello, take the liberty of disturbing you. I haven't found the evaluation criteria for each instrument source, and it seems that I can't well judge that the instrument can be separated from a single 3D point cloud frame.
![image](https://user-images.githubusercontent.com/64669901/136726123-f01726c6-e2b3-44c3-a95a-bf843a96e89a.png)
Thank you for your answer!

**Comment by francesclluis** [comment]
Hi!
We evaluate the source separation performance with regard to the number of sources N present in the mix. For evaluation, we use the bss_eval_sources() function.

**Comment by yangdaowu** [comment]
Thank you for your answer, and then I want to add evaluation indicators for each source, such as cello. But I don't know how to do it.
